### ISSUE TITLE
IATI organisation filter still has non IATI organisations in the list

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#563] opened 2020-05-26 13:16 UTC
See screenshot, it should be impossible to select an organisation in the IATI filter and get no result as the organisations list is generated from the IATI data!

![Screenshot from 2020-05-26 15-15-06](https://user-images.githubusercontent.com/432153/82905198-d86fb680-9f63-11ea-8aaf-575fb0835b0d.png)

**Comment by raashidahmad** [comment] 2020-05-30 06:20
@matmaxgeds The issue is that we are extracting organizations differently from the activities. Organizations are extracted at application load or every night with new IATI load. While we show only active activities on demand requested through UI.
I will have to think over it on how this can be sorted out.

**Comment by matmaxgeds** [comment] 2020-05-30 06:33
Thanks Rashid, I understand that issue, I guess it is about pulling the
iati_orgs list from the subset of active IATI activities, not from the full
list.

However, I also see orgs on the iati_org dropdown that I am surprised to
see there because I don't think that they are from IATI but they look like
AIMS orgs e. g. Turkey, so please double check that.

**Comment by raashidahmad** [comment] 2020-06-25 09:48
@matmaxgeds this fixed. Please review. Closing it, we may open it if there are any concerns.

**Closed by raashidahmad** 2020-06-25 09:48 UTC
Labels: Bug, Data entry, Phase 1
